### ISSUE TITLE
Documentation overhaul checklist

### ISSUE THREAD

**Issue by maaleske** [maaleske/hsicube#2]
## Description

Detailed and consistent documentation (visible with MATLAB `help` or `doc`) should be available for

- [x] Cube object properties
- [x] Cube object methods
- [x] ENVI object methods

In addition, tutorials or examples should be written for common usecases, such as

- [x] ENVI reading / writing
- [ ] Setting and inspecting Cube properties
- [x] Workflow example for some hyperspectral analysis task

Please comment if you have suggestions for example cases!
